DROP DATABASE IF EXISTS AJUNTAMENT;
CREATE DATABASE AJUNTAMENT;
USE AJUNTAMENT;

CREATE TABLE RECINTE(
PK_CODI_RECINTE INT auto_increment NOT NULL,
NOM_RECINTE VARCHAR(100) NOT NULL,
DIRECCIO varchar(200) NOT NULL,
CAPACITAT INT,

primary KEY (PK_CODI_RECINTE)
);


CREATE TABLE ESDEVENIMENT(
PK_ID_ESDEVENIMENT INT auto_increment,
FK_CODI_RECINTE INT NOT NULL,
NOM varchar(100) NOT NULL,
DESCRIPCIO varchar(700),
HORA date NOT NULL,
DATA_INICI date NOT NULL,
DATA_FI DATE NOT NULL,
PREU DECIMAL(7, 2) DEFAULT 0,

primary key (PK_ID_ESDEVENIMENT),

CONSTRAINT FK_CODI_RECINTE FOREIGN KEY (PK_CODI_RECINTE)
REFERENCES RECINTE (PK_CODI_RECINTE)
);

CREATE TABLE TIPUS(
PK_CODI_TIPUS INT auto_increment,
NOM_TIPUS varchar(100) NOT NULL,

primary key (PK_CODI_TIPUS)
);

CREATE TABLE PERSONA(
PK_CODI_PERSONA INT auto_increment NOT NULL,
DNI VARCHAR(20),/*DNI també pot significar NIF, passaport, etc.*/
NOM varchar(50) NOT NULL,
LLINATGES varchar(100) NOT NULL,
EMAIL VARCHAR(100),
DATA_NAIXEMENT date NOT NULL,

primary key (PK_CODI_PERSONA)
);

CREATE TABLE TELEFON_PERSONA(
PK_NUMERO_PERSONA INT NOT NULL,
PK_FK_CODI_PERSONA INT NOT NULL,
TIPUS_NUMERO VARCHAR(100),
OBSERVACIONS varchar(300),

primary key (PK_NUMERO_PERSONA, PK_FK_CODI_PERSONA),

CONSTRAINT PK_FK_CODI_PERSONA FOREIGN KEY (PK_CODI_PERSONA)
REFERENCES PERSONA (PK_CODI_PERSONA)

);

CREATE TABLE ENTRADA(
PK_NUMERO_ENTRADA INT auto_increment NOT null,
PK_FK_ID_ESDEVENIMENT INT NOT NULL,
FK_CODI_PERSONA int NOT NULL,
DESCOMPTE VARCHAR(10),
DATA_ENTRADA datetime NOT null,

primary KEY (PK_NUMERO_ENTRADA, PK_FK_ID_ESDEVENIMENT),

CONSTRAINT PK_FK_ID_ESDEVENIMENT FOREIGN KEY (PK_ID_ESDEVENIMENT)--
REFERENCES ENTRADA (PK_NUMERO_ENTRADA)--
);

CREATE TABLE PUNT_VENTA(
PK_CODI_PUNT_VENTA INT auto_increment NOT NULL,
FK_NUMERO_ENTRADA INT NOT NULL,
NOM VARCHAR(100) NOT NULL,
WEB VARCHAR(300),
EMAIL varchar(300),
DIRECCIO VARCHAR(200),

primary KEY (PK_CODI_PUNT_VENTA),

CONSTRAINT FK_NUMERO_ENTRADA FOREIGN KEY (PK_NUMERO_ENTRADA)--
REFERENCES ENTRADA (PK_NUMERO_ENTRADA)--
);

CREATE TABLE TELEFON_PUNT_VENTA(
PK_NUMERO_PUNT_VENTA INT auto_increment NOT NULL,
PK_FK_CODI_PUNT_VENTA INT NOT NULL,
TIPUS_NUMERO VARCHAR(100),
OBSERVACIONS varchar(300),

primary key(PK_NUMERO_PUNT_VENTA, PK_FK_CODI_PUNT_VENTA)
);

CREATE TABLE RESTRICCIO(
PK_CODI_RESTRICCIO INT auto_increment NOT NULL,
PK_FK_ID_ESDEVENIMENT INT NOT NULL,
TIPUS_RESTRICCIO VARCHAR(100),
DESCRIPCIO VARCHAR (300),

PRIMARY KEY (PK_CODI_RESTRICCIO, PK_FK_ID_ESDEVENIMENT),


);

CREATE TABLE PAGA(
PK_FK_CODI_PERSONA INT NOT NULL,
PK_FK_NUMERO_ENTRADA INT NOT NULL,

primary KEY (PK_FK_CODI_PERSONA , PK_FK_NUMERO_ENTRADA)
);

CREATE TABLE TIPUS_ESDEVENIMENT(
PK_FK_CODI_TIPUS INT NOT NULL,
PK_FK_ID_ESDEVENIMENT INT NOT NULL,

PRIMARY KEY (PK_FK_CODI_TIPUS,PK_FK_ID_ESDEVENIMENT)
);

/*----AFEGIM CONSTRAINTS-----*/
/*CONSTRAINTS A ESDEVENIMENT*/
