DROP DATABASE IF EXISTS AJUNTAMENT;
CREATE DATABASE AJUNTAMENT;
USE AJUNTAMENT;

CREATE TABLE RECINTE(
PK_CODI_RECINTE INT auto_increment NOT NULL,
NOM_RECINTE VARCHAR(100) NOT NULL,
DIRECCIO varchar(200) NOT NULL,
CAPACITAT INT,

primary KEY (PK_CODI_RECINTE)
);

CREATE TABLE BUTACA(
PK_FK_CODI_RECINTE INT NOT NULL,
PK_FILA_BUTACA INT NOT NULL,
PK_NUMERO_BUTACA INT NOT NULL,

primary key (PK_FK_CODI_RECINTE, PK_FILA_BUTACA, PK_NUMERO_BUTACA)
);

CREATE TABLE ESDEVENIMENT(
PK_ID_ESDEVENIMENT INT auto_increment NOT NULL,
NOM varchar(100) NOT NULL,
DESCRIPCIO varchar(700),
DATA_INICI DATETIME NOT NULL,
DATA_FI DATETIME NOT NULL,
PREU DECIMAL(7, 2) DEFAULT 0,
AFORAMENT INT NOT NULL DEFAULT 0,
OCUPACIO INT NOT NULL DEFAULT 0,

FK_CODI_RECINTE INT NOT NULL,

primary key (PK_ID_ESDEVENIMENT)
);

CREATE TABLE TIPUS(
PK_CODI_TIPUS INT auto_increment NOT NULL,
NOM_TIPUS varchar(100) NOT NULL,

primary key (PK_CODI_TIPUS)
);

CREATE TABLE PERSONA(
PK_CODI_PERSONA INT auto_increment NOT NULL,
DNI VARCHAR(20),/*DNI també pot significar NIF, passaport, etc.*/
NOM varchar(50) NOT NULL,
LLINATGES varchar(100) NOT NULL,
EMAIL VARCHAR(100),
DATA_NAIXEMENT DATE,

primary key (PK_CODI_PERSONA)
);

CREATE TABLE TELEFON_PERSONA(
PK_TELEFON_PERSONA INT NOT NULL,
PK_FK_CODI_PERSONA INT NOT NULL,
TIPUS_TELEFON VARCHAR(100),
OBSERVACIONS varchar(300),

primary key (PK_TELEFON_PERSONA, PK_FK_CODI_PERSONA)
);

CREATE TABLE PUNT_VENTA(
PK_CODI_PUNT_VENTA INT auto_increment NOT NULL,
NOM VARCHAR(100) NOT NULL,
WEB VARCHAR(300),
EMAIL varchar(300),
DIRECCIO VARCHAR(200),

primary KEY (PK_CODI_PUNT_VENTA)
);

CREATE TABLE ENTRADA(
PK_FK_ID_ENTRADA_ESDEVENIMENT INT NOT NULL,
PK_NUMERO_ENTRADA INT auto_increment NOT null,
DESCOMPTE VARCHAR(10),
DATA_ENTRADA datetime NOT null,

FK_CODI_PUNT_VENTA INT NOT NULL,
FK_CODI_PERSONA int,
FK_CODI_RECINTE INT NOT NULL,
FK_FILA_BUTACA INT,
FK_NUMERO_BUTACA INT,

primary KEY (PK_NUMERO_ENTRADA, PK_FK_ID_ENTRADA_ESDEVENIMENT)
);

CREATE TABLE TELEFON_PUNT_VENTA(
PK_TELEFON_PUNT_VENTA INT auto_increment NOT NULL,
PK_FK_CODI_PUNT_VENTA INT NOT NULL,
TIPUS_NUMERO VARCHAR(100),
OBSERVACIONS varchar(300),

primary key(PK_TELEFON_PUNT_VENTA, PK_FK_CODI_PUNT_VENTA)
);

CREATE TABLE RESTRICCIO(
PK_CODI_RESTRICCIO INT auto_increment NOT NULL,
PK_FK_ID_RESTRICCIO_ESDEVENIMENT INT NOT NULL,
TIPUS_RESTRICCIO VARCHAR(100),
DESCRIPCIO VARCHAR (300),

PRIMARY KEY (PK_CODI_RESTRICCIO, PK_FK_ID_RESTRICCIO_ESDEVENIMENT)
);

CREATE TABLE TIPUS_ESDEVENIMENT(
PK_FK_CODI_TIPUS INT NOT NULL,
PK_FK_ID_TIPUS_ESDEVENIMENT INT NOT NULL,

PRIMARY KEY (PK_FK_CODI_TIPUS,PK_FK_ID_TIPUS_ESDEVENIMENT)
);

CREATE TABLE RESTRICCIO_ESDEVENIMENT(
PK_FK_CODI_RESTRICCIO INT NOT NULL,
PK_FK_ID_REST_ESDEVENIMENT INT NOT NULL,

primary key (PK_FK_CODI_RESTRICCIO, PK_FK_ID_REST_ESDEVENIMENT)
);


/*-------------------------------AFEGIM CONSTRAINTS---------------------------------*/
/*CONSTRAINTS A BUTACA*/
ALTER TABLE BUTACA ADD CONSTRAINT PK_FK_CODI_RECINTE FOREIGN KEY (PK_FK_CODI_RECINTE)
REFERENCES RECINTE (PK_CODI_RECINTE) ON UPDATE CASCADE ON DELETE CASCADE;

/*CONSTRAINTS A ESDEVENIMENT*/
ALTER TABLE ESDEVENIMENT ADD CONSTRAINT FK_CODI_RECINTE FOREIGN KEY (FK_CODI_RECINTE)
REFERENCES RECINTE(PK_CODI_RECINTE) ON UPDATE CASCADE ON DELETE RESTRICT;

/*CONSTRAINTS A TELEFON_PERSONA*/
ALTER TABLE TELEFON_PERSONA ADD CONSTRAINT PK_FK_CODI_PERSONA FOREIGN KEY (PK_FK_CODI_PERSONA)
REFERENCES PERSONA (PK_CODI_PERSONA) ON UPDATE CASCADE ON DELETE CASCADE;

/*CONSTRAINTS A ENTRADA*/
ALTER TABLE ENTRADA ADD CONSTRAINT PK_FK_ID_ENTRADA_ESDEVENIMENT FOREIGN KEY (PK_FK_ID_ENTRADA_ESDEVENIMENT)
REFERENCES ESDEVENIMENT (PK_ID_ESDEVENIMENT) ON UPDATE CASCADE ON DELETE RESTRICT;
--
ALTER TABLE ENTRADA ADD CONSTRAINT FK_CODI_PUNT_VENTA FOREIGN KEY (FK_CODI_PUNT_VENTA)
REFERENCES PUNT_VENTA (PK_CODI_PUNT_VENTA) ON UPDATE CASCADE ON DELETE RESTRICT;
--
ALTER TABLE ENTRADA ADD CONSTRAINT FK_CODI_PERSONA FOREIGN KEY (FK_CODI_PERSONA)
REFERENCES PERSONA (PK_CODI_PERSONA) ON UPDATE CASCADE ON DELETE RESTRICT;
--
ALTER TABLE ENTRADA ADD CONSTRAINT FK_BUTACA FOREIGN KEY (FK_CODI_RECINTE, FK_FILA_BUTACA, FK_NUMERO_BUTACA)
REFERENCES BUTACA (PK_FK_CODI_RECINTE, PK_FILA_BUTACA, PK_NUMERO_BUTACA) ON UPDATE CASCADE ON DELETE RESTRICT;

/*CONSTRAINTS A TELEFON_PUNT_VENTA*/
ALTER TABLE TELEFON_PUNT_VENTA ADD CONSTRAINT PK_FK_CODI_PUNT_VENTA FOREIGN KEY (PK_FK_CODI_PUNT_VENTA)
REFERENCES PUNT_VENTA (PK_CODI_PUNT_VENTA) ON UPDATE CASCADE ON DELETE CASCADE;

/*CONSTRAINTS A RESTRICCIO*/
ALTER TABLE RESTRICCIO ADD CONSTRAINT PK_FK_ID_RESTRICCIO_ESDEVENIMENT FOREIGN KEY (PK_FK_ID_RESTRICCIO_ESDEVENIMENT)
REFERENCES ESDEVENIMENT (PK_ID_ESDEVENIMENT) ON UPDATE CASCADE ON DELETE CASCADE;

/*CONSTRAINTS A TIPUS_ESDEVENIMENT*/
ALTER TABLE TIPUS_ESDEVENIMENT ADD CONSTRAINT PK_FK_CODI_TIPUS FOREIGN KEY (PK_FK_CODI_TIPUS)
REFERENCES TIPUS (PK_CODI_TIPUS) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE TIPUS_ESDEVENIMENT ADD CONSTRAINT PK_FK_ID_TIPUS_ESDEVENIMENT FOREIGN KEY (PK_FK_ID_TIPUS_ESDEVENIMENT)
REFERENCES ESDEVENIMENT (PK_ID_ESDEVENIMENT) ON UPDATE CASCADE ON DELETE RESTRICT;

/*CONSTRAINTS A RESTRICCIO_ESDEVENIMENT*/
ALTER TABLE RESTRICCIO_ESDEVENIMENT ADD CONSTRAINT PK_FK_CODI_RESTRICCIO FOREIGN KEY (PK_FK_CODI_RESTRICCIO)
REFERENCES RESTRICCIO (PK_CODI_RESTRICCIO) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE RESTRICCIO_ESDEVENIMENT ADD CONSTRAINT PK_FK_ID_REST_ESDEVENIMENT FOREIGN KEY (PK_FK_ID_REST_ESDEVENIMENT)
REFERENCES ESDEVENIMENT (PK_ID_ESDEVENIMENT) ON UPDATE CASCADE ON DELETE RESTRICT;
