/*INSERTS PERSONA*/

INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (1, '815', 'Mr.', 'Sheridan', 'kiera39@example.org', '1988-06-09');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (2, '730', 'Dr.', 'Herman', 'zieme.rosemary@example.net', '1999-09-03');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (3, '145', 'Prof.', 'Alfonso', 'amy.ritchie@example.com', '1983-07-04');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (4, '322', 'Mr.', 'Emie', 'mathew.halvorson@example.net', '1997-08-30');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (5, '366', 'Prof.', 'Carlee', 'bartoletti.dorian@example.com', '1986-04-14');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (6, '055', 'Prof.', 'Stephan', 'gbraun@example.org', '1995-01-12');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (7, '915', 'Mr.', 'Velva', 'rtorphy@example.org', '1991-09-24');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (8, '804', 'Mr.', 'Ally', 'fisher.laurie@example.com', '1976-09-25');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (9, '692', 'Mr.', 'Mossie', 'denesik.chanel@example.net', '1980-06-03');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (10, '755', 'Mr.', 'Woodrow', 'koelpin.tierra@example.net', '1987-01-20');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (11, '206', 'Mr.', 'Aimee', 'ikutch@example.org', '2006-02-10');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (12, '808', 'Prof.', 'Theodora', 'thad.sauer@example.com', '2009-07-27');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (13, '386', 'Dr.', 'Brandt', 'langosh.leatha@example.com', '2003-10-09');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (14, '820', 'Dr.', 'Roger', 'fbailey@example.com', '2006-09-23');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (15, '590', 'Mr.', 'Clementina', 'raphaelle14@example.com', '1972-11-20');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (16, '422', 'Prof.', 'Dora', 'benny.berge@example.org', '1990-06-25');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (17, '230', 'Dr.', 'Krystal', 'laurie83@example.org', '1999-09-13');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (18, '601', 'Mr.', 'Sedrick', 'glen76@example.net', '2016-01-22');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (19, '412', 'Dr.', 'Wilton', 'jayne.king@example.org', '1995-10-22');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (20, '231', 'Mr.', 'Clare', 'fwilliamson@example.com', '1990-03-03');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (21, '844', 'Prof.', 'Sunny', 'ukuhic@example.com', '2000-07-18');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (22, '970', 'Mr.', 'Yasmin', 'tfarrell@example.com', '1991-06-20');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (23, '000', 'Prof.', 'Haylie', 'paucek.virgie@example.com', '2009-12-24');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (24, '813', 'Mr.', 'Sasha', 'rmueller@example.com', '1985-04-23');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (25, '728', 'Mr.', 'Reece', 'humberto.bode@example.net', '1976-08-19');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (26, '487', 'Prof.', 'Ron', 'blanda.jonathon@example.com', '1973-12-25');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (27, '024', 'Prof.', 'Deja', 'jermaine98@example.net', '2010-02-21');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (28, '671', 'Mr.', 'Martin', 'chester75@example.org', '2000-12-22');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (29, '330', 'Prof.', 'Shayna', 'khermiston@example.net', '1988-09-15');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (30, '365', 'Prof.', 'Filiberto', 'madams@example.org', '1977-11-28');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (31, '643', 'Mr.', 'Sadie', 'huels.colton@example.com', '1974-01-17');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (32, '139', 'Mr.', 'Frederick', 'maia24@example.net', '1995-07-10');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (33, '144', 'Mr.', 'Lempi', 'jaydon58@example.net', '2003-04-23');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (34, '767', 'Dr.', 'Thalia', 'hcruickshank@example.com', '2011-10-01');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (35, '778', 'Dr.', 'Alessia', 'hiram.lebsack@example.org', '1983-11-11');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (36, '389', 'Mr.', 'Kathryn', 'darrell92@example.net', '2008-03-06');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (37, '055', 'Mr.', 'Domenica', 'ferry.ethel@example.com', '1982-11-02');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (38, '370', 'Prof.', 'Anastasia', 'pete.runolfsdottir@example.org', '1979-03-19');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (39, '573', 'Mr.', 'Theodore', 'johnston.maddison@example.org', '2017-05-25');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (40, '198', 'Prof.', 'Donavon', 'jazmin.batz@example.net', '1981-04-16');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (41, '022', 'Mr.', 'Raven', 'reilly.jayda@example.net', '1979-04-26');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (42, '051', 'Prof.', 'Damion', 'murray.jaunita@example.net', '1987-01-18');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (43, '176', 'Prof.', 'Winston', 'rpfeffer@example.com', '1997-05-05');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (44, '146', 'Prof.', 'Riley', 'smitham.karen@example.org', '2009-12-08');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (45, '066', 'Dr.', 'Alaina', 'opowlowski@example.net', '2015-11-23');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (46, '855', 'Mr.', 'Amiya', 'conroy.dorris@example.com', '2016-09-26');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (47, '815', 'Mr.', 'Willy', 'rahul06@example.net', '1998-05-15');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (48, '873', 'Mr.', 'Kirk', 'demond85@example.com', '2014-10-02');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (49, '085', 'Mr.', 'Sibyl', 'vonrueden.allene@example.org', '2014-06-30');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (50, '229', 'Dr.', 'Maybelle', 'ahammes@example.org', '2011-09-16');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (51, '835', 'Dr.', 'Natasha', 'rollin72@example.com', '2011-08-31');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (52, '329', 'Dr.', 'Nicklaus', 'wisoky.ulises@example.com', '1990-02-17');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (53, '928', 'Prof.', 'Earnestine', 'ebradtke@example.org', '2002-01-13');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (54, '317', 'Mr.', 'Marianna', 'wrussel@example.com', '2012-06-18');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (55, '932', 'Dr.', 'Darrel', 'kiarra40@example.com', '1985-02-09');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (56, '484', 'Mr.', 'Madelynn', 'llangosh@example.org', '2015-08-06');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (57, '214', 'Mr.', 'Milford', 'd\'angelo.macejkovic@example.org', '1997-01-28');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (58, '315', 'Dr.', 'Sherman', 'loren53@example.org', '1995-06-08');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (59, '463', 'Dr.', 'Karelle', 'eichmann.cordia@example.net', '1978-06-14');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (60, '897', 'Prof.', 'Presley', 'napoleon57@example.net', '2014-06-14');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (61, '876', 'Dr.', 'Jayne', 'george.dubuque@example.net', '1985-12-28');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (62, '285', 'Prof.', 'Pedro', 'riley85@example.org', '1981-12-30');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (63, '133', 'Mr.', 'Franz', 'corkery.magnolia@example.org', '1987-04-18');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (64, '638', 'Mr.', 'Anita', 'buckridge.antonio@example.net', '1973-01-24');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (65, '995', 'Mr.', 'Ferne', 'wunsch.hollie@example.com', '1975-04-03');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (66, '268', 'Prof.', 'Esta', 'gregoria.quigley@example.net', '2001-12-29');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (67, '331', 'Mr.', 'Kaley', 'annalise.towne@example.com', '2013-09-07');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (68, '712', 'Dr.', 'Ottilie', 'isom.jones@example.net', '1997-11-04');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (69, '427', 'Mr.', 'Priscilla', 'gulgowski.kaelyn@example.com', '2001-10-05');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (70, '854', 'Prof.', 'Sam', 'torp.makayla@example.net', '1999-09-19');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (71, '433', 'Mr.', 'Hassan', 'vlueilwitz@example.com', '1977-06-15');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (72, '634', 'Mr.', 'Alan', 'rath.marian@example.com', '1987-03-14');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (73, '944', 'Dr.', 'Pattie', 'justice12@example.net', '1994-05-07');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (74, '060', 'Prof.', 'Emerald', 'sipes.zaria@example.com', '1980-04-08');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (75, '663', 'Prof.', 'Diana', 'nflatley@example.com', '2011-01-15');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (76, '077', 'Mr.', 'Lizeth', 'nader.alana@example.com', '1970-01-04');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (77, '408', 'Dr.', 'Joesph', 'delfina.goldner@example.org', '2014-03-15');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (78, '578', 'Mr.', 'Jaden', 'baumbach.hillard@example.net', '1983-03-14');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (79, '701', 'Mr.', 'Gretchen', 'grant.jerrod@example.net', '2008-08-25');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (80, '844', 'Mr.', 'Jaida', 'hsanford@example.org', '2004-04-27');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (81, '108', 'Prof.', 'Isobel', 'ralph.jacobson@example.net', '1978-04-22');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (82, '787', 'Mr.', 'Clyde', 'mertz.elisha@example.org', '1978-01-25');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (83, '204', 'Prof.', 'Jordi', 'feil.damon@example.net', '2012-05-31');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (84, '842', 'Prof.', 'Laila', 'alysha.beahan@example.net', '1985-12-13');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (85, '536', 'Dr.', 'Adriel', 'everett08@example.com', '1990-03-23');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (86, '137', 'Mr.', 'Rosemarie', 'whilll@example.net', '1991-08-01');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (87, '082', 'Mr.', 'Ashlee', 'nader.jayda@example.com', '1974-10-23');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (88, '060', 'Mr.', 'Margot', 'huel.arch@example.org', '1973-10-04');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (89, '449', 'Prof.', 'Rick', 'ebert.claire@example.com', '1988-12-02');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (90, '159', 'Mr.', 'Adele', 'kylee81@example.net', '1984-09-17');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (91, '706', 'Prof.', 'Bette', 'prohaska.brant@example.net', '2005-09-15');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (92, '862', 'Dr.', 'Orin', 'jarod.kuhn@example.org', '1984-05-11');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (93, '644', 'Dr.', 'Olen', 'bernhard.esther@example.com', '2001-10-31');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (94, '471', 'Prof.', 'Davonte', 'uhowell@example.net', '1987-05-31');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (95, '799', 'Dr.', 'Jerald', 'smueller@example.com', '1979-10-07');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (96, '732', 'Mr.', 'Katelynn', 'pfeffer.jared@example.net', '1998-12-01');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (97, '723', 'Dr.', 'Trent', 'hhermann@example.net', '2015-12-20');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (98, '847', 'Dr.', 'Tate', 'corkery.vivienne@example.com', '2018-11-11');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (99, '469', 'Prof.', 'Vidal', 'edythe.flatley@example.org', '1992-01-21');
INSERT INTO `PERSONA` (`PK_CODI_PERSONA`, `DNI`, `NOM`, `LLINATGES`, `EMAIL`, `DATA_NAIXEMENT`) VALUES (100, '237', 'Mr.', 'Edmond', 'deron.block@example.com', '2002-08-05');

/*INSERTS INTO TELEFON_PERSONA*/

INSERT INTO `TELEFON_PERSONA` (`PK_TELEFON_PERSONA`, `PK_FK_CODI_PERSONA`, `TIPUS_TELEFON`, `OBSERVACIONS`) VALUES (1, 8, 'in', 'Et minima perspiciatis fugit voluptatem enim.');
INSERT INTO `TELEFON_PERSONA` (`PK_TELEFON_PERSONA`, `PK_FK_CODI_PERSONA`, `TIPUS_TELEFON`, `OBSERVACIONS`) VALUES (1, 60, 'id', 'Id aperiam omnis fugiat in porro quo aut.');
INSERT INTO `TELEFON_PERSONA` (`PK_TELEFON_PERSONA`, `PK_FK_CODI_PERSONA`, `TIPUS_TELEFON`, `OBSERVACIONS`) VALUES (2, 1, 'aspernatur', 'Cum velit veritatis maiores saepe et nesciunt voluptates vel.');
INSERT INTO `TELEFON_PERSONA` (`PK_TELEFON_PERSONA`, `PK_FK_CODI_PERSONA`, `TIPUS_TELEFON`, `OBSERVACIONS`) VALUES (2, 9, 'odit', 'Dicta ducimus omnis eveniet minus.');
INSERT INTO `TELEFON_PERSONA` (`PK_TELEFON_PERSONA`, `PK_FK_CODI_PERSONA`, `TIPUS_TELEFON`, `OBSERVACIONS`) VALUES (5, 2, 'ducimus', 'Et quae dignissimos impedit blanditiis.');
INSERT INTO `TELEFON_PERSONA` (`PK_TELEFON_PERSONA`, `PK_FK_CODI_PERSONA`, `TIPUS_TELEFON`, `OBSERVACIONS`) VALUES (26, 33, 'minima', 'Earum dolores eos dolores quam rerum culpa blanditiis.');
INSERT INTO `TELEFON_PERSONA` (`PK_TELEFON_PERSONA`, `PK_FK_CODI_PERSONA`, `TIPUS_TELEFON`, `OBSERVACIONS`) VALUES (41, 52, 'a', 'Et ea nemo illum ipsum aut sunt inventore vel.');
INSERT INTO `TELEFON_PERSONA` (`PK_TELEFON_PERSONA`, `PK_FK_CODI_PERSONA`, `TIPUS_TELEFON`, `OBSERVACIONS`) VALUES (150, 5, 'optio', 'Molestias est sit totam sit odio.');
INSERT INTO `TELEFON_PERSONA` (`PK_TELEFON_PERSONA`, `PK_FK_CODI_PERSONA`, `TIPUS_TELEFON`, `OBSERVACIONS`) VALUES (252, 60, 'nobis', 'Iusto veniam animi veniam non quos.');
INSERT INTO `TELEFON_PERSONA` (`PK_TELEFON_PERSONA`, `PK_FK_CODI_PERSONA`, `TIPUS_TELEFON`, `OBSERVACIONS`) VALUES (499, 5, 'officiis', 'Reiciendis cupiditate qui vitae voluptatem assumenda.');
INSERT INTO `TELEFON_PERSONA` (`PK_TELEFON_PERSONA`, `PK_FK_CODI_PERSONA`, `TIPUS_TELEFON`, `OBSERVACIONS`) VALUES (1008, 7, 'explicabo', 'Error iusto cumque eos ut possimus corrupti.');
INSERT INTO `TELEFON_PERSONA` (`PK_TELEFON_PERSONA`, `PK_FK_CODI_PERSONA`, `TIPUS_TELEFON`, `OBSERVACIONS`) VALUES (1900, 23, 'veritatis', 'Sapiente magnam libero rerum sed corporis commodi quo.');
INSERT INTO `TELEFON_PERSONA` (`PK_TELEFON_PERSONA`, `PK_FK_CODI_PERSONA`, `TIPUS_TELEFON`, `OBSERVACIONS`) VALUES (2920, 41, 'et', 'Laudantium saepe architecto quasi provident qui.');
INSERT INTO `TELEFON_PERSONA` (`PK_TELEFON_PERSONA`, `PK_FK_CODI_PERSONA`, `TIPUS_TELEFON`, `OBSERVACIONS`) VALUES (6911, 5, 'ad', 'Officiis optio aspernatur quae voluptas et unde saepe.');
INSERT INTO `TELEFON_PERSONA` (`PK_TELEFON_PERSONA`, `PK_FK_CODI_PERSONA`, `TIPUS_TELEFON`, `OBSERVACIONS`) VALUES (8823, 3, 'sit', 'Veritatis quia dolorem perspiciatis tenetur.');
INSERT INTO `TELEFON_PERSONA` (`PK_TELEFON_PERSONA`, `PK_FK_CODI_PERSONA`, `TIPUS_TELEFON`, `OBSERVACIONS`) VALUES (33125, 63, 'et', 'Et ab quo aut.');
INSERT INTO `TELEFON_PERSONA` (`PK_TELEFON_PERSONA`, `PK_FK_CODI_PERSONA`, `TIPUS_TELEFON`, `OBSERVACIONS`) VALUES (38076, 20, 'possimus', 'Accusantium officia laborum est harum.');
INSERT INTO `TELEFON_PERSONA` (`PK_TELEFON_PERSONA`, `PK_FK_CODI_PERSONA`, `TIPUS_TELEFON`, `OBSERVACIONS`) VALUES (603251, 42, 'perspiciatis', 'Sunt maxime quo ea eaque quo.');
INSERT INTO `TELEFON_PERSONA` (`PK_TELEFON_PERSONA`, `PK_FK_CODI_PERSONA`, `TIPUS_TELEFON`, `OBSERVACIONS`) VALUES (11917099, 86, 'aut', 'Est est id provident error rerum perspiciatis rerum.');

/*INSERTS INTO PUNT_VENTA*/

INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (1, 'eos', 'Sint occaecati id dolores hic aspernatur beatae maiores asperiores.', 'janessa79@example.net', 'Culpa quia officia porro qui saepe numquam repellendus debitis.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (2, 'expedita', 'Consequatur nemo consequatur laudantium facere aut culpa dignissimos cum.', 'judy92@example.net', 'Consequuntur enim quia odio.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (3, 'id', 'Qui in ipsum totam eos neque voluptas.', 'mathias25@example.com', 'Illo libero enim ut quis.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (4, 'quia', 'In tempora voluptas maxime ut quis est nulla.', 'darwin.gleichner@example.com', 'Amet impedit vero et fugit est reiciendis nulla.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (5, 'magni', 'Sunt a nisi perferendis officiis.', 'mervin.ullrich@example.net', 'Cumque repellendus sit vero quam totam fuga fugiat.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (6, 'aut', 'Veniam voluptatem excepturi est et est et.', 'katrine52@example.net', 'Nihil nesciunt dicta omnis officiis aliquid sit in.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (7, 'in', 'Iusto voluptatem consequatur fuga rerum vero sed quisquam perspiciatis.', 'nichole.yundt@example.net', 'Consequatur autem eos qui molestiae et ratione quia qui.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (8, 'itaque', 'Magnam nemo in et voluptas aut aut fugit.', 'wehner.darrel@example.org', 'Cumque asperiores eum et beatae incidunt.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (9, 'cupiditate', 'Voluptas laborum assumenda non eos.', 'pmacejkovic@example.net', 'Et velit voluptatum voluptas sequi laudantium atque quisquam.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (10, 'quis', 'Natus reiciendis omnis aperiam a.', 'moore.brain@example.net', 'Animi temporibus ea qui repudiandae.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (11, 'voluptas', 'Quisquam rerum dolorum veritatis.', 'lkozey@example.com', 'Quasi ab vel occaecati veniam ut alias.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (12, 'illo', 'Et hic sit voluptate suscipit consequatur deserunt iusto.', 'dannie.dickens@example.net', 'Velit doloremque excepturi quia ab eligendi eaque aut delectus.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (13, 'voluptas', 'Qui ut aut iusto et.', 'marlon.cremin@example.org', 'Et ea modi aut quibusdam ut.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (14, 'temporibus', 'Et praesentium id minus sed.', 'gussie.willms@example.org', 'Dolore at voluptas itaque nihil est laboriosam.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (15, 'eos', 'Corrupti provident assumenda inventore debitis officiis odit sed.', 'ahoppe@example.net', 'Quis omnis culpa mollitia sed repudiandae.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (16, 'delectus', 'Numquam id cum praesentium expedita consequuntur ipsam.', 'reuben14@example.org', 'Et maxime pariatur qui et eligendi distinctio consequatur quo.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (17, 'ut', 'Eaque ut saepe aut perspiciatis.', 'santa.crist@example.net', 'Voluptatem eligendi odit rerum sunt eum est eveniet.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (18, 'ex', 'Enim expedita ullam voluptatem aut asperiores in recusandae debitis.', 'reilly.rafaela@example.com', 'Suscipit dolores illum aut illum voluptate non voluptatem.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (19, 'aut', 'Suscipit facilis sint et et qui reiciendis nulla dolorum.', 'milo70@example.org', 'Eos vel sed dolorum iure.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (20, 'omnis', 'Voluptas sint exercitationem exercitationem aut rerum voluptatem id.', 'vgreenholt@example.net', 'Nesciunt cum saepe voluptas aut.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (21, 'non', 'Voluptas aut eos necessitatibus.', 'qwyman@example.net', 'Natus perferendis aliquid hic quaerat dolorum tenetur cum.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (22, 'est', 'Provident voluptas est consequatur culpa repellat praesentium.', 'sydney98@example.org', 'Consequatur officiis excepturi sunt.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (23, 'asperiores', 'Expedita perspiciatis vel excepturi aperiam optio ab vel.', 'lharber@example.com', 'Non sit alias explicabo nisi ut optio.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (24, 'officiis', 'Est qui aut dolore repellat.', 'yhessel@example.com', 'Inventore sed sint occaecati rerum natus et rem.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (25, 'non', 'Quasi nisi et illum mollitia voluptas.', 'soledad65@example.com', 'Voluptatem dolores qui adipisci doloremque sunt delectus aut.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (26, 'totam', 'Nihil esse vitae consequuntur.', 'rschiller@example.com', 'Veritatis quae qui est ab.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (27, 'voluptatem', 'Nihil officiis ut labore totam.', 'jason.jakubowski@example.net', 'Laudantium est eligendi dolor odit sed fuga.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (28, 'similique', 'Beatae sapiente quia repudiandae qui.', 'oswald93@example.com', 'Est maiores et nemo illum natus beatae et saepe.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (29, 'alias', 'Qui vel omnis quae.', 'ludie.howe@example.com', 'Rerum rerum aliquid aliquam pariatur cum nam repellendus.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (30, 'magni', 'Itaque dolor et doloribus ut rerum.', 'yweimann@example.com', 'Similique alias magni repudiandae.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (31, 'tempore', 'Asperiores distinctio error delectus dolor architecto vel a.', 'fanny94@example.com', 'Tempora dolorem laborum quia fugiat quo quia consequatur.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (32, 'esse', 'Molestiae pariatur ab voluptatem est quam.', 'dschowalter@example.org', 'Commodi temporibus molestiae velit consequatur temporibus amet vel.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (33, 'eveniet', 'Tempora reiciendis sunt tempore.', 'ron81@example.net', 'Amet fugit ut dolorum laudantium repudiandae temporibus dolores quod.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (34, 'nam', 'Nulla et quia doloremque animi optio.', 'dorcas.shanahan@example.net', 'Qui possimus beatae quas excepturi alias laborum expedita.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (35, 'saepe', 'Sequi dolores illum error temporibus distinctio.', 'blang@example.org', 'Amet dolorum veniam vitae maxime non.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (36, 'doloremque', 'Nulla ut iste consectetur veritatis accusamus dolorem culpa.', 'lbosco@example.org', 'Quia ut natus rerum natus libero.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (37, 'cum', 'Neque delectus itaque dolorem consequuntur velit.', 'hswift@example.com', 'Quaerat temporibus amet non vel.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (38, 'in', 'Non aut omnis qui nihil voluptate tempora.', 'earmstrong@example.org', 'Eum totam natus et facilis.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (39, 'velit', 'Ea totam dolorum cum.', 'daugherty.thelma@example.net', 'Reprehenderit aut cum aliquam repudiandae repudiandae.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (40, 'error', 'Repellat in sint quibusdam ab.', 'lester.jerde@example.com', 'Quibusdam cupiditate illo magni neque.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (41, 'aut', 'Voluptatibus non distinctio voluptatem provident.', 'cole89@example.com', 'Est qui nulla provident et blanditiis cumque hic.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (42, 'laborum', 'Reprehenderit quia corrupti nobis id incidunt.', 'stracke.dewayne@example.com', 'Ea ut est magni qui.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (43, 'enim', 'Omnis quam voluptas ut sunt repellendus.', 'durward.mcglynn@example.net', 'Enim vitae consectetur necessitatibus earum accusamus corrupti provident fugiat.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (44, 'dolores', 'Mollitia odit qui id sed voluptas voluptatem officia autem.', 'wdavis@example.org', 'Voluptatem qui inventore rerum atque ab cupiditate.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (45, 'amet', 'Quo distinctio fugiat cumque repellat et perferendis.', 'jerad42@example.net', 'Sed dolores sed magnam in maxime.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (46, 'omnis', 'Accusamus cum natus soluta animi ad beatae architecto voluptatum.', 'rbeer@example.com', 'Rem earum qui consequatur itaque vitae suscipit dolores.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (47, 'doloribus', 'Nobis a sint nulla culpa possimus optio.', 'kuphal.rodger@example.net', 'Possimus autem exercitationem harum ut et dolor commodi omnis.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (48, 'ipsum', 'Quis at tenetur distinctio voluptates qui.', 'syundt@example.org', 'Distinctio corrupti doloremque adipisci natus porro ipsa.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (49, 'excepturi', 'Molestiae aliquam esse enim debitis placeat velit.', 'caroline.stamm@example.com', 'Qui blanditiis non recusandae dicta ratione aliquam aliquam.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (50, 'non', 'Possimus ullam reprehenderit eos omnis aliquam sit.', 'janiya.bernhard@example.net', 'Minus eveniet consequatur eos quia quidem.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (51, 'aspernatur', 'Voluptatem repudiandae eos cupiditate delectus.', 'dbruen@example.net', 'Maxime et omnis non fugiat vel non voluptas omnis.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (52, 'ut', 'Molestiae adipisci et dicta aspernatur aut.', 'karson58@example.com', 'Praesentium aliquid voluptatum qui explicabo.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (53, 'cumque', 'Aperiam est quia velit qui.', 'kaia.mohr@example.net', 'Est quo ratione consequatur sequi tenetur veniam.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (54, 'eligendi', 'Quibusdam occaecati doloremque asperiores.', 'ipfannerstill@example.net', 'Tempora nulla ut repellendus ad adipisci.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (55, 'qui', 'Et facere eius sunt porro non.', 'rudy.russel@example.org', 'Vel sed explicabo ut voluptas illo.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (56, 'qui', 'Quos quidem voluptate reiciendis illum eveniet quisquam.', 'donnie08@example.com', 'Quia qui laudantium dolorum officia veritatis.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (57, 'incidunt', 'Et omnis officia adipisci ipsam voluptatibus dolorem.', 'glenda59@example.net', 'Odio sint ea nulla voluptatem.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (58, 'ullam', 'Cumque cum tempore debitis sed ducimus pariatur dicta.', 'luz06@example.com', 'Est officia minima est sit.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (59, 'maiores', 'Corrupti blanditiis sit debitis dolorem ullam aut voluptatem sint.', 'mheathcote@example.org', 'Delectus velit porro quidem aspernatur incidunt accusamus.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (60, 'temporibus', 'Omnis id harum excepturi sapiente consectetur.', 'murray.cordia@example.com', 'Maiores id beatae sed vero blanditiis pariatur magnam.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (61, 'quia', 'Et autem dolores nesciunt rerum sunt.', 'yoberbrunner@example.org', 'Laudantium sequi possimus reiciendis minima odit error.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (62, 'maxime', 'Exercitationem ea error inventore vero recusandae.', 'marks.stanton@example.net', 'Sed veritatis est aspernatur deserunt.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (63, 'quas', 'Recusandae reiciendis qui quia assumenda unde quia ex ab.', 'gerlach.gerry@example.org', 'Explicabo occaecati perferendis eum et ut praesentium labore.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (64, 'ut', 'Omnis cumque necessitatibus molestias magni commodi saepe accusantium.', 'tjacobi@example.org', 'Cupiditate voluptates facere placeat aut.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (65, 'consectetur', 'Quam possimus sunt et officia ut earum qui.', 'jaren83@example.org', 'Libero eos est suscipit cum.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (66, 'consequatur', 'Voluptates dolor ea eligendi ea voluptas praesentium reprehenderit.', 'turner.wunsch@example.com', 'Provident rerum et accusamus corporis adipisci et.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (67, 'quas', 'Similique doloremque reprehenderit neque optio.', 'rconsidine@example.org', 'Molestiae quia illum quia sapiente ut sint exercitationem.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (68, 'consectetur', 'Quos minus est magni.', 'collier.millie@example.com', 'Ipsum harum sed aliquid.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (69, 'quasi', 'Doloremque expedita iste deleniti possimus molestiae saepe quis consequuntur.', 'walker.kira@example.com', 'Aliquam sit rerum dolorem voluptate vitae illum.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (70, 'aut', 'Sint sed architecto officiis debitis voluptatem ipsum.', 'golden01@example.net', 'Assumenda sunt expedita dolorum rem aut neque modi.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (71, 'reiciendis', 'Provident sed aut sed deleniti quia.', 'wilkinson.jude@example.org', 'Officia doloribus aliquid quia natus tenetur deserunt.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (72, 'quia', 'Similique est ut ea vero eligendi et.', 'ikuhlman@example.net', 'Aperiam quidem necessitatibus rem vel itaque.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (73, 'optio', 'Voluptate beatae et qui ea in quis.', 'bartell.neal@example.net', 'Voluptatum odit ratione in omnis.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (74, 'totam', 'Ex est rerum placeat atque velit illum architecto.', 'bernhard.bettye@example.com', 'Et corporis molestiae delectus vitae iste sit.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (75, 'doloremque', 'Est pariatur delectus qui amet.', 'jacobi.esteban@example.com', 'Eligendi libero pariatur et dolore velit qui cum.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (76, 'corrupti', 'Aut eligendi ut veritatis et odio.', 'shaniya.russel@example.com', 'Voluptatem laudantium dolores recusandae numquam totam.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (77, 'quis', 'Odio et ex hic quo harum.', 'felipe.balistreri@example.org', 'Ut maiores non id eligendi illo.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (78, 'est', 'Quam eveniet quam totam qui quaerat.', 'garrison44@example.com', 'Similique quae rerum voluptatum minus sed perspiciatis occaecati quia.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (79, 'quo', 'Earum in molestiae ea eos quisquam quasi.', 'dereck24@example.net', 'Consequatur animi ut velit cupiditate quod dolor maiores ea.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (80, 'dolor', 'Qui amet et dolores dolore nulla magni.', 'diana.bode@example.com', 'Deserunt saepe quo aut natus et.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (81, 'pariatur', 'Laudantium non libero quia molestiae deleniti.', 'allison.bartell@example.org', 'Molestiae quia minima ducimus magni voluptas illum.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (82, 'iure', 'Porro dolor et vel.', 'malvina.klein@example.net', 'Sequi facere ut vel dicta.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (83, 'est', 'Suscipit ipsam ipsam est.', 'shad21@example.net', 'Soluta doloribus magnam molestias porro ex illo laudantium.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (84, 'hic', 'At soluta libero quia vitae.', 'corkery.kacie@example.com', 'Cum et enim voluptate repellendus neque praesentium aspernatur.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (85, 'dicta', 'Eveniet voluptatum expedita magni dolores aliquam maiores.', 'amani.gusikowski@example.net', 'Consequatur dolorem ea eum consequatur minima facere.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (86, 'quo', 'Blanditiis molestiae nemo sunt deleniti.', 'stamm.mayra@example.org', 'Ea veniam repudiandae totam dicta ut quas.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (87, 'minima', 'Repellendus magni labore adipisci.', 'stanton.cortez@example.org', 'Corporis fuga ut nobis tempore.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (88, 'accusamus', 'Aut et eos ut possimus non inventore voluptatibus.', 'jkirlin@example.org', 'Ut voluptatum sit qui rerum.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (89, 'aspernatur', 'Ipsam quod molestiae et ipsum cum laboriosam qui.', 'cassandra.kunde@example.net', 'Labore totam eos modi et natus aut sit.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (90, 'aut', 'Nemo odio nobis voluptatem.', 'dimitri.ritchie@example.org', 'Optio rerum odio fugiat dolores aut rerum.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (91, 'odio', 'Labore deserunt voluptas et voluptate reprehenderit aliquid dolorem possimus.', 'ccormier@example.org', 'Nihil cupiditate vero eum ratione voluptates voluptas.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (92, 'consectetur', 'Alias laborum ut odio ut molestiae deleniti voluptas.', 'roma.haag@example.org', 'Iure doloribus ut blanditiis dolores ab.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (93, 'ullam', 'Ut sed ut omnis incidunt non ea.', 'bjaskolski@example.com', 'Esse et voluptates labore provident aut dolor est.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (94, 'ea', 'Id veniam est necessitatibus minima eveniet sit.', 'camilla.stark@example.org', 'Atque cum at voluptatem accusamus consequatur.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (95, 'voluptas', 'Dolorem in quos perspiciatis qui quibusdam eveniet.', 'garret27@example.com', 'Possimus voluptatem eos quisquam sit aut similique occaecati.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (96, 'similique', 'Maxime sed quisquam distinctio dicta autem.', 'elaina32@example.com', 'A dolores sunt ut molestiae omnis autem dolorem.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (97, 'nemo', 'Quaerat occaecati at ipsum architecto.', 'ymosciski@example.net', 'Nihil dolores exercitationem voluptas quia rem praesentium.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (98, 'qui', 'Quia ipsa sit quos commodi animi.', 'tprice@example.org', 'Architecto enim voluptate in aut deserunt aliquid voluptas.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (99, 'quasi', 'Voluptatem quod quia rerum reprehenderit placeat beatae consequatur.', 'terrell.prosacco@example.net', 'Maiores voluptatibus velit adipisci aliquam soluta neque.');
INSERT INTO `PUNT_VENTA` (`PK_CODI_PUNT_VENTA`, `NOM`, `WEB`, `EMAIL`, `DIRECCIO`) VALUES (100, 'magnam', 'Accusamus modi tempore assumenda enim animi.', 'qlittel@example.org', 'Explicabo illum velit iusto id voluptatem.');

/*INSERTS INTO TELEFON_PUNT_VENTA*/

INSERT INTO `TELEFON_PUNT_VENTA` (`PK_TELEFON_PUNT_VENTA`, `PK_FK_CODI_PUNT_VENTA`, `TIPUS_NUMERO`, `OBSERVACIONS`) VALUES (104, 7, 'voluptatem', 'Ut rerum deleniti reprehenderit in et sit et praesentium.');
INSERT INTO `TELEFON_PUNT_VENTA` (`PK_TELEFON_PUNT_VENTA`, `PK_FK_CODI_PUNT_VENTA`, `TIPUS_NUMERO`, `OBSERVACIONS`) VALUES (105, 10, 'expedita', 'Consequuntur doloremque nihil voluptas eos ratione aut doloribus.');
INSERT INTO `TELEFON_PUNT_VENTA` (`PK_TELEFON_PUNT_VENTA`, `PK_FK_CODI_PUNT_VENTA`, `TIPUS_NUMERO`, `OBSERVACIONS`) VALUES (116, 4, 'voluptatum', 'Alias quibusdam perspiciatis debitis quasi.');
INSERT INTO `TELEFON_PUNT_VENTA` (`PK_TELEFON_PUNT_VENTA`, `PK_FK_CODI_PUNT_VENTA`, `TIPUS_NUMERO`, `OBSERVACIONS`) VALUES (118, 5, 'aut', 'Alias voluptas alias corporis repellendus.');
INSERT INTO `TELEFON_PUNT_VENTA` (`PK_TELEFON_PUNT_VENTA`, `PK_FK_CODI_PUNT_VENTA`, `TIPUS_NUMERO`, `OBSERVACIONS`) VALUES (121, 1, 'rerum', 'Rerum aut natus dolores laudantium pariatur totam temporibus accusantium.');
INSERT INTO `TELEFON_PUNT_VENTA` (`PK_TELEFON_PUNT_VENTA`, `PK_FK_CODI_PUNT_VENTA`, `TIPUS_NUMERO`, `OBSERVACIONS`) VALUES (128, 22, 'voluptatem', 'Voluptate facilis tenetur rerum.');
INSERT INTO `TELEFON_PUNT_VENTA` (`PK_TELEFON_PUNT_VENTA`, `PK_FK_CODI_PUNT_VENTA`, `TIPUS_NUMERO`, `OBSERVACIONS`) VALUES (133, 14, 'voluptatum', 'Quia molestiae quasi id quibusdam facere.');
INSERT INTO `TELEFON_PUNT_VENTA` (`PK_TELEFON_PUNT_VENTA`, `PK_FK_CODI_PUNT_VENTA`, `TIPUS_NUMERO`, `OBSERVACIONS`) VALUES (136, 66, 'nisi', 'Consequatur consequuntur quia eligendi earum debitis similique magnam.');
INSERT INTO `TELEFON_PUNT_VENTA` (`PK_TELEFON_PUNT_VENTA`, `PK_FK_CODI_PUNT_VENTA`, `TIPUS_NUMERO`, `OBSERVACIONS`) VALUES (137, 48, 'laborum', 'Corrupti consequatur nam sit saepe doloremque ipsam.');
INSERT INTO `TELEFON_PUNT_VENTA` (`PK_TELEFON_PUNT_VENTA`, `PK_FK_CODI_PUNT_VENTA`, `TIPUS_NUMERO`, `OBSERVACIONS`) VALUES (151, 58, 'praesentium', 'Voluptatibus in natus cumque quae neque porro.');
INSERT INTO `TELEFON_PUNT_VENTA` (`PK_TELEFON_PUNT_VENTA`, `PK_FK_CODI_PUNT_VENTA`, `TIPUS_NUMERO`, `OBSERVACIONS`) VALUES (153, 36, 'voluptatem', 'Minima est dicta quas commodi atque.');
INSERT INTO `TELEFON_PUNT_VENTA` (`PK_TELEFON_PUNT_VENTA`, `PK_FK_CODI_PUNT_VENTA`, `TIPUS_NUMERO`, `OBSERVACIONS`) VALUES (155, 8, 'dolores', 'Nesciunt veritatis porro blanditiis aut.');
INSERT INTO `TELEFON_PUNT_VENTA` (`PK_TELEFON_PUNT_VENTA`, `PK_FK_CODI_PUNT_VENTA`, `TIPUS_NUMERO`, `OBSERVACIONS`) VALUES (156, 9, 'cumque', 'Deserunt et nisi illo aspernatur.');
INSERT INTO `TELEFON_PUNT_VENTA` (`PK_TELEFON_PUNT_VENTA`, `PK_FK_CODI_PUNT_VENTA`, `TIPUS_NUMERO`, `OBSERVACIONS`) VALUES (159, 13, 'autem', 'Ducimus dolorem totam quia aliquid ut soluta.');
INSERT INTO `TELEFON_PUNT_VENTA` (`PK_TELEFON_PUNT_VENTA`, `PK_FK_CODI_PUNT_VENTA`, `TIPUS_NUMERO`, `OBSERVACIONS`) VALUES (163, 89, 'repellendus', 'Provident deleniti ut maxime dignissimos ea.');
INSERT INTO `TELEFON_PUNT_VENTA` (`PK_TELEFON_PUNT_VENTA`, `PK_FK_CODI_PUNT_VENTA`, `TIPUS_NUMERO`, `OBSERVACIONS`) VALUES (164, 79, 'quam', 'Quae cumque sed rerum facilis aliquam.');
INSERT INTO `TELEFON_PUNT_VENTA` (`PK_TELEFON_PUNT_VENTA`, `PK_FK_CODI_PUNT_VENTA`, `TIPUS_NUMERO`, `OBSERVACIONS`) VALUES (174, 68, 'sunt', 'Non et numquam quas rerum optio minima.');
INSERT INTO `TELEFON_PUNT_VENTA` (`PK_TELEFON_PUNT_VENTA`, `PK_FK_CODI_PUNT_VENTA`, `TIPUS_NUMERO`, `OBSERVACIONS`) VALUES (178, 39, 'soluta', 'Quia tempore quibusdam error nam consequatur et.');
INSERT INTO `TELEFON_PUNT_VENTA` (`PK_TELEFON_PUNT_VENTA`, `PK_FK_CODI_PUNT_VENTA`, `TIPUS_NUMERO`, `OBSERVACIONS`) VALUES (180, 6, 'voluptatem', 'Molestiae cupiditate nihil quaerat necessitatibus ut eos sunt ea.');
INSERT INTO `TELEFON_PUNT_VENTA` (`PK_TELEFON_PUNT_VENTA`, `PK_FK_CODI_PUNT_VENTA`, `TIPUS_NUMERO`, `OBSERVACIONS`) VALUES (183, 85, 'tempore', 'Odio recusandae eum adipisci.');
INSERT INTO `TELEFON_PUNT_VENTA` (`PK_TELEFON_PUNT_VENTA`, `PK_FK_CODI_PUNT_VENTA`, `TIPUS_NUMERO`, `OBSERVACIONS`) VALUES (184, 80, 'quidem', 'Sunt nesciunt qui ipsa voluptas officia quidem laudantium possimus.');
INSERT INTO `TELEFON_PUNT_VENTA` (`PK_TELEFON_PUNT_VENTA`, `PK_FK_CODI_PUNT_VENTA`, `TIPUS_NUMERO`, `OBSERVACIONS`) VALUES (189, 41, 'dolorem', 'Et vitae est earum laudantium sapiente dolor impedit.');
INSERT INTO `TELEFON_PUNT_VENTA` (`PK_TELEFON_PUNT_VENTA`, `PK_FK_CODI_PUNT_VENTA`, `TIPUS_NUMERO`, `OBSERVACIONS`) VALUES (190, 28, 'adipisci', 'Qui sed laborum tempore cupiditate.');
INSERT INTO `TELEFON_PUNT_VENTA` (`PK_TELEFON_PUNT_VENTA`, `PK_FK_CODI_PUNT_VENTA`, `TIPUS_NUMERO`, `OBSERVACIONS`) VALUES (193, 2, 'qui', 'Consequatur ut et sapiente non nemo minus numquam.');
INSERT INTO `TELEFON_PUNT_VENTA` (`PK_TELEFON_PUNT_VENTA`, `PK_FK_CODI_PUNT_VENTA`, `TIPUS_NUMERO`, `OBSERVACIONS`) VALUES (198, 73, 'vitae', 'Dolorum est consequatur libero cum et velit.');

/*INSERTS INTO RECINTE*/

INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (1, 'deserunt', 'In reiciendis totam non amet et tempora incidunt.', 8334589);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (2, 'omnis', 'Animi ipsum vel blanditiis explicabo ullam autem excepturi.', 876192187);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (3, 'ab', 'Impedit deleniti esse molestiae commodi.', 0);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (4, 'deleniti', 'Nemo vero vitae non consectetur.', 8);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (5, 'tempora', 'Dicta sit ut et accusantium.', 10212);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (6, 'voluptate', 'Itaque quam beatae a.', 27);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (7, 'consequatur', 'Odio autem in enim non eaque.', 82603);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (8, 'id', 'Magni repudiandae distinctio odio quia ut eligendi.', 86);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (9, 'consequatur', 'Iure repellat soluta aliquam cumque ipsum odit et.', 267397468);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (10, 'a', 'Quae beatae ad voluptatem ipsam.', 344);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (11, 'numquam', 'Porro ut vitae distinctio commodi quasi qui.', 494);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (12, 'facere', 'Et possimus non voluptas et ullam molestiae eos eaque.', 772635);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (13, 'rerum', 'Eos et qui molestiae et et tenetur eum.', 3);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (14, 'corporis', 'Nam qui aliquid autem modi quis.', 7852166);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (15, 'enim', 'Laudantium qui voluptatem accusantium natus.', 1841);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (16, 'optio', 'Aut aut et nam ut dolorem expedita iste atque.', 55);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (17, 'commodi', 'Tempore aperiam quia eos ut fuga totam.', 0);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (18, 'ipsa', 'Excepturi quis laborum vero atque voluptas.', 38631);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (19, 'consequuntur', 'Fuga commodi eum ut.', 3956741);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (20, 'atque', 'Quibusdam deleniti quae cupiditate rerum.', 819);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (21, 'doloribus', 'Aut consequatur veniam reprehenderit ut.', 8948945);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (22, 'error', 'Explicabo sint blanditiis asperiores eaque aut.', 796);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (23, 'hic', 'Mollitia eum aut eos veritatis aliquid earum quis.', 2343198);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (24, 'quidem', 'Quas cumque provident aliquam magnam sed accusamus ratione.', 869510963);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (25, 'consequuntur', 'Repudiandae rerum ad illum aut quia.', 646168);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (26, 'sapiente', 'Sed eos vitae numquam vel aut.', 0);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (27, 'impedit', 'Modi sint ipsam atque eum voluptas.', 87);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (28, 'repellendus', 'Consequatur incidunt minus qui vitae laboriosam sed.', 255602072);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (29, 'atque', 'Veniam vero deserunt quibusdam ea ut consequatur.', 2);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (30, 'necessitatibus', 'Quae molestiae sit praesentium sed autem sunt.', 7340);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (31, 'corrupti', 'Sunt eos quo voluptas architecto laborum culpa sunt.', 47);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (32, 'qui', 'Cupiditate repudiandae dolor fugiat est ex.', 467);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (33, 'quae', 'Illo nobis illum architecto dolor recusandae.', 982509624);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (34, 'id', 'Aliquam expedita neque autem nulla.', 712);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (35, 'non', 'Ut deleniti qui facere quidem et labore.', 7596275);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (36, 'inventore', 'Debitis est qui fuga.', 7287);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (37, 'in', 'Nemo dicta voluptatem consequatur voluptas.', 0);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (38, 'consequatur', 'Quod ea qui dolorem in omnis eius.', 0);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (39, 'impedit', 'Nulla ex modi eaque rerum excepturi.', 29848993);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (40, 'et', 'Aliquid vitae dolor ad eaque ratione.', 6121);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (41, 'nesciunt', 'Odio perspiciatis est est voluptatem reiciendis officia.', 62);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (42, 'sed', 'Quo est itaque in delectus et.', 0);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (43, 'ipsam', 'Id corrupti blanditiis nam voluptatum corporis non sunt qui.', 0);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (44, 'explicabo', 'Soluta porro et itaque ratione assumenda.', 7);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (45, 'voluptas', 'Non iure commodi odio aspernatur et voluptas.', 1645);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (46, 'maxime', 'Et voluptas laboriosam quo quaerat ab officiis laborum.', 21726);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (47, 'placeat', 'At excepturi sunt est quisquam.', 88833);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (48, 'omnis', 'Dicta minus non commodi natus exercitationem iure sunt itaque.', 53);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (49, 'reprehenderit', 'Vitae quo et non id modi illo adipisci.', 9);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (50, 'non', 'Quae reprehenderit et porro quia amet soluta temporibus.', 91);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (51, 'ratione', 'Rerum eos et qui et vitae iure.', 603);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (52, 'nulla', 'Assumenda et et expedita qui quo.', 114316);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (53, 'est', 'Cupiditate et molestiae voluptatibus perferendis.', 1);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (54, 'voluptatem', 'Sapiente quisquam et eius sequi voluptatibus.', 488);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (55, 'libero', 'Aspernatur nesciunt fugiat iste voluptatum voluptatem et aperiam.', 0);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (56, 'aspernatur', 'Quo dignissimos commodi eaque pariatur numquam earum autem.', 8016);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (57, 'ratione', 'Necessitatibus corrupti soluta aliquam animi rerum id voluptatem.', 436);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (58, 'consequatur', 'Iste ea perspiciatis aspernatur qui perspiciatis suscipit inventore.', 0);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (59, 'nesciunt', 'Recusandae a in illo ut nemo nesciunt dolorem.', 666);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (60, 'ea', 'Et saepe quo ut debitis.', 17);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (61, 'ut', 'Quae accusamus dolore deserunt consequatur.', 680);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (62, 'accusamus', 'Deleniti consectetur qui et.', 11);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (63, 'doloribus', 'Voluptas voluptatem ipsam nostrum cupiditate repellendus odio.', 41);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (64, 'recusandae', 'Autem magni totam voluptatem sit eius.', 24173);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (65, 'odit', 'Repellendus alias maiores in ex voluptas quis.', 503605);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (66, 'aspernatur', 'Vitae sint modi dolor facilis iusto consequatur.', 39);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (67, 'vel', 'Explicabo incidunt quaerat in veniam voluptates nisi.', 5265);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (68, 'quasi', 'Suscipit facilis sit nesciunt laboriosam.', 29407940);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (69, 'eos', 'Placeat impedit quia consectetur.', 88112);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (70, 'est', 'Sunt et consectetur est.', 21627883);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (71, 'perferendis', 'Totam ut nihil aut et.', 12142);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (72, 'hic', 'Ab deserunt molestiae et molestiae officia eum.', 0);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (73, 'laborum', 'Odit rerum possimus et nihil veritatis.', 462439628);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (74, 'nulla', 'Aut rerum quis non mollitia animi corrupti consequatur.', 6);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (75, 'eos', 'Nulla accusantium architecto a incidunt et est.', 3957);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (76, 'qui', 'Iure minima perspiciatis sunt.', 465);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (77, 'rerum', 'Praesentium iure ut inventore.', 0);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (78, 'porro', 'Corporis sed at est corrupti.', 47024);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (79, 'quo', 'Reiciendis ad ab cum nobis atque eligendi iusto.', 0);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (80, 'quos', 'Eos ea eligendi quasi quia inventore.', 74573832);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (81, 'minima', 'Dignissimos earum sit consectetur et.', 2);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (82, 'non', 'Fugit reiciendis reiciendis labore quo numquam.', 7725);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (83, 'omnis', 'Ipsum qui excepturi exercitationem earum magnam consequuntur nisi.', 515);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (84, 'dolorum', 'Enim eum et illum asperiores voluptatem ut.', 484827129);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (85, 'impedit', 'Aliquam cumque eligendi animi possimus voluptatum omnis.', 5417105);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (86, 'eos', 'Voluptas voluptate laboriosam autem aut.', 5744);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (87, 'eaque', 'Velit ratione assumenda quia maxime cumque.', 76);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (88, 'qui', 'Voluptates autem odit doloribus tenetur qui.', 4249);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (89, 'non', 'Blanditiis ut animi excepturi quibusdam nisi aut incidunt aut.', 761);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (90, 'quos', 'Sapiente ut ea repudiandae eos libero sapiente.', 3);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (91, 'vero', 'Nostrum cum assumenda molestiae architecto rem tenetur.', 2245);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (92, 'nostrum', 'Minus culpa dolore consequatur.', 37494);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (93, 'temporibus', 'Exercitationem nostrum facere in.', 1);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (94, 'commodi', 'Voluptas sed omnis facere ratione beatae vel consequatur.', 790268);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (95, 'tempora', 'Id qui qui ea sint eaque.', 5);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (96, 'tenetur', 'Iusto assumenda voluptas repudiandae sed.', 953422799);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (97, 'aliquid', 'Sapiente eius rerum quis non quam.', 114);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (98, 'dolore', 'Fuga doloribus omnis vel sed sed sed consequatur.', 49);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (99, 'autem', 'Ipsam quod amet aut est mollitia et rem id.', 59421491);
INSERT INTO `RECINTE` (`PK_CODI_RECINTE`, `NOM_RECINTE`, `DIRECCIO`, `CAPACITAT`) VALUES (100, 'sint', 'Aut et possimus non debitis aut.', 6602415);

/*INSERTS INTO TIPUS*/

INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (1, 'Dolor rerum id dicta aut veritatis nam.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (2, 'Qui officia excepturi iure tempora vel.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (3, 'Mollitia sint aut minus et id perferendis minus.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (4, 'Ex dignissimos debitis a ab aperiam.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (5, 'Rem eius adipisci et ducimus aperiam quia voluptas veniam.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (6, 'Id et dolores beatae omnis.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (7, 'Beatae saepe nisi laudantium ut.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (8, 'Earum eos est quas omnis sit exercitationem.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (9, 'Doloremque aperiam distinctio voluptatem quasi et.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (10, 'Sit quo iusto magnam consequuntur.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (11, 'Alias quas eos occaecati ipsa animi laudantium.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (12, 'Itaque aut ut velit explicabo sit eligendi exercitationem.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (13, 'Sit velit dignissimos est et alias.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (14, 'Nam et qui quo aut esse quam facilis numquam.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (15, 'Fugiat omnis similique quia.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (16, 'Reiciendis labore corporis dicta aliquam.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (17, 'Ad perspiciatis repellendus in.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (18, 'Vero voluptatem exercitationem sunt voluptatibus.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (19, 'Assumenda non consequatur quibusdam magni aut.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (20, 'Officia ratione minus mollitia eveniet debitis.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (21, 'Iste eos magnam aut adipisci hic.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (22, 'Ad eos odit praesentium nihil dicta quaerat.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (23, 'Laborum possimus quam consequatur id consequatur sapiente sunt dolor.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (24, 'Minus quis sunt voluptatum et consequatur.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (25, 'Earum ut consectetur necessitatibus ipsam qui id officia.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (26, 'Blanditiis provident dolorem dolores expedita.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (27, 'Beatae aspernatur explicabo vel consequatur et minus illo ducimus.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (28, 'Maiores culpa repudiandae eos saepe.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (29, 'Autem suscipit et temporibus aut quibusdam.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (30, 'Aut neque sit minima excepturi.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (31, 'Et ullam dolore non qui recusandae quibusdam.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (32, 'Consequatur facere sequi eos eos et et est officiis.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (33, 'Quia rem eos accusantium quis molestias quis autem.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (34, 'Perspiciatis vel omnis magnam et quos.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (35, 'Quia facere et et eos beatae quis sed.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (36, 'Veniam itaque laboriosam voluptatem praesentium nostrum ab.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (37, 'Doloremque facere quia necessitatibus error corporis.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (38, 'Porro magnam dolore asperiores quibusdam ad aut excepturi.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (39, 'Consequatur pariatur dolor optio velit fugit possimus nemo.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (40, 'Odit earum laborum sint officia quia.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (41, 'Officiis perspiciatis veritatis illo veniam eius et aut doloremque.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (42, 'Nihil ea exercitationem et tempora vero.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (43, 'Voluptatem libero et reprehenderit alias nesciunt id.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (44, 'Vel suscipit velit possimus asperiores.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (45, 'Id ut ut sed accusamus aut cum.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (46, 'Voluptas nam at dolorem laudantium excepturi.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (47, 'Placeat quam possimus laborum ut est corrupti nihil.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (48, 'Aspernatur molestiae rem odio omnis impedit.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (49, 'Atque hic excepturi et unde asperiores incidunt quia.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (50, 'Sed est et unde aliquam ullam eos est sit.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (51, 'Et a eligendi quia ea.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (52, 'Aut sapiente consectetur ut impedit ut ipsam dolorem et.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (53, 'Vel aut sit facere veritatis.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (54, 'Sit laudantium accusantium eveniet nemo.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (55, 'Qui repellat aperiam in ut alias vel cumque.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (56, 'Qui odit aut est ut omnis.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (57, 'Sunt aut qui officia illo aliquam occaecati id molestias.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (58, 'Beatae debitis reiciendis quia excepturi quis voluptatem dolores.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (59, 'Esse occaecati quod dolores culpa voluptatibus aut.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (60, 'Ut maiores quia aut et dolores.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (61, 'Doloremque quasi iure quaerat ut alias est.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (62, 'Impedit incidunt vitae atque.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (63, 'Et vel aliquam enim quia quaerat et ab.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (64, 'Eos dolores autem corrupti at officiis ea et.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (65, 'Est ut quibusdam maxime unde facere.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (66, 'Maxime aperiam reprehenderit nam.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (67, 'Eos necessitatibus quae asperiores.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (68, 'Quasi voluptatem velit facilis et mollitia ut eveniet.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (69, 'Enim a eaque fugit sed repellendus.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (70, 'Ut sit id recusandae qui id est facilis.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (71, 'Fugit deserunt sed eum asperiores in et.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (72, 'Pariatur assumenda ex repellat ducimus et earum sunt.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (73, 'Adipisci illum aut consequuntur cum itaque.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (74, 'Sed quae eum doloribus ea.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (75, 'Ipsum assumenda assumenda quod nesciunt mollitia et.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (76, 'Nostrum sequi dolorem nisi accusantium.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (77, 'Hic eligendi esse qui esse esse quae ab veniam.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (78, 'Vel et sint minima rerum.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (79, 'Sit est reprehenderit quo iste.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (80, 'Minus itaque sint in porro recusandae dolor laboriosam.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (81, 'Reprehenderit totam necessitatibus facilis corporis sunt sed unde.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (82, 'Vitae reprehenderit eaque magni possimus.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (83, 'Possimus sed vel a consequatur excepturi ipsam qui.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (84, 'Aut aliquid aliquam iste ratione qui velit.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (85, 'Officiis quis tenetur fugiat recusandae perspiciatis.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (86, 'Et sint iure minima soluta quo.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (87, 'Dolor et repellat beatae sit.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (88, 'Consequatur et cum recusandae at.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (89, 'Odit reprehenderit culpa et exercitationem.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (90, 'Quis commodi veniam amet rerum amet rerum.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (91, 'Dicta eius nobis nisi.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (92, 'Deserunt aut dolor magni et illo facere placeat officia.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (93, 'Sit distinctio rem deserunt rerum doloribus est.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (94, 'Tempora sed optio quasi reiciendis consequatur.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (95, 'Voluptas itaque vitae repudiandae ipsam distinctio cumque laboriosam.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (96, 'Eveniet aut et non ut aut.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (97, 'Rerum velit hic nesciunt laboriosam esse similique dolorum.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (98, 'Ratione sequi aut neque ut ut unde est.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (99, 'Dignissimos laboriosam nesciunt provident odit minima.');
INSERT INTO `TIPUS` (`PK_CODI_TIPUS`, `NOM_TIPUS`) VALUES (100, 'Sequi omnis delectus aut quo mollitia ut voluptate.');

/*INSERTS INTO ESDEVENIMENT*/
INSERT INTO `ESDEVENIMENT` (`PK_ID_ESDEVENIMENT`, `NOM`, `DESCRIPCIO`, `HORA`, `DATA_INICI`, `DATA_FI`, `PREU`, `FK_CODI_RECINTE`) VALUES (103, 'in', 'Mollitia pariatur praesentium quisquam et eos minima labore repudiandae. Fugit et aliquid ex animi nisi. Optio ducimus veritatis cum repellendus tenetur. Quos praesentium soluta itaque rerum est.', '2004-07-25', '1981-01-19', '1981-10-18', '99999.99', 9);
INSERT INTO `ESDEVENIMENT` (`PK_ID_ESDEVENIMENT`, `NOM`, `DESCRIPCIO`, `HORA`, `DATA_INICI`, `DATA_FI`, `PREU`, `FK_CODI_RECINTE`) VALUES (105, 'molestias', 'Molestiae consequuntur hic alias qui ab deleniti ipsam voluptatem. Quos facere nemo blanditiis eaque vitae iusto. Quaerat et animi ad exercitationem tempore dolorem.', '2007-06-07', '1984-05-22', '1975-12-08', '1338.00', 66);
INSERT INTO `ESDEVENIMENT` (`PK_ID_ESDEVENIMENT`, `NOM`, `DESCRIPCIO`, `HORA`, `DATA_INICI`, `DATA_FI`, `PREU`, `FK_CODI_RECINTE`) VALUES (107, 'maiores', 'Cum cum sequi sit officiis. Aut eos non ut aut. Ad officiis consequatur nam non. Nostrum ullam qui est labore id voluptatem.', '2004-02-16', '1996-10-08', '2001-12-27', '0.00', 76);
INSERT INTO `ESDEVENIMENT` (`PK_ID_ESDEVENIMENT`, `NOM`, `DESCRIPCIO`, `HORA`, `DATA_INICI`, `DATA_FI`, `PREU`, `FK_CODI_RECINTE`) VALUES (114, 'earum', 'Explicabo quibusdam nihil odio nihil porro sapiente. Ex id voluptatem quos voluptate non rem magnam. Blanditiis rem illum quas a hic atque. Minima adipisci eum doloremque architecto quo adipisci.', '2018-12-17', '2001-09-17', '1970-02-08', '8446.00', 4);
INSERT INTO `ESDEVENIMENT` (`PK_ID_ESDEVENIMENT`, `NOM`, `DESCRIPCIO`, `HORA`, `DATA_INICI`, `DATA_FI`, `PREU`, `FK_CODI_RECINTE`) VALUES (116, 'saepe', 'Molestiae quis commodi fuga vel quibusdam labore. Officiis dolor quidem quia sed. Qui commodi dolores beatae molestiae iste dolore eos. Dolorum nostrum aut aut dolores molestias delectus.', '1971-07-15', '1980-11-10', '2003-09-18', '6616.00', 8);
INSERT INTO `ESDEVENIMENT` (`PK_ID_ESDEVENIMENT`, `NOM`, `DESCRIPCIO`, `HORA`, `DATA_INICI`, `DATA_FI`, `PREU`, `FK_CODI_RECINTE`) VALUES (117, 'doloremque', 'Consequatur molestias reprehenderit et quidem. Quis aperiam et vitae. Dolorem quaerat officia dolorem natus adipisci. Odio dolores commodi enim aliquam laborum consequatur.', '2018-09-21', '2014-07-17', '1995-09-10', '99999.99', 5);
INSERT INTO `ESDEVENIMENT` (`PK_ID_ESDEVENIMENT`, `NOM`, `DESCRIPCIO`, `HORA`, `DATA_INICI`, `DATA_FI`, `PREU`, `FK_CODI_RECINTE`) VALUES (127, 'voluptate', 'Harum autem dolores facilis fugiat et exercitationem quae distinctio. Culpa quibusdam amet ea similique numquam nisi id. Blanditiis magni tempora rerum. Aut doloremque est repellat qui sit.', '1984-07-24', '1977-05-23', '2012-08-16', '338.00', 6);
INSERT INTO `ESDEVENIMENT` (`PK_ID_ESDEVENIMENT`, `NOM`, `DESCRIPCIO`, `HORA`, `DATA_INICI`, `DATA_FI`, `PREU`, `FK_CODI_RECINTE`) VALUES (128, 'itaque', 'Dolorem temporibus itaque autem qui illo temporibus. Alias ipsam debitis aut non veritatis cum voluptatibus quia. Odit sit hic omnis ab dolor numquam ad.', '2000-05-01', '2014-05-14', '1977-02-28', '94.00', 3);
INSERT INTO `ESDEVENIMENT` (`PK_ID_ESDEVENIMENT`, `NOM`, `DESCRIPCIO`, `HORA`, `DATA_INICI`, `DATA_FI`, `PREU`, `FK_CODI_RECINTE`) VALUES (135, 'nesciunt', 'Laborum eius nihil pariatur repellendus est et. Velit saepe eum doloremque optio voluptatem soluta voluptatum beatae.', '1978-11-07', '2015-06-16', '2007-03-25', '99999.99', 87);
INSERT INTO `ESDEVENIMENT` (`PK_ID_ESDEVENIMENT`, `NOM`, `DESCRIPCIO`, `HORA`, `DATA_INICI`, `DATA_FI`, `PREU`, `FK_CODI_RECINTE`) VALUES (139, 'animi', 'Molestiae architecto beatae est hic. Consequatur quas sed quis mollitia quo. Tenetur cum iure velit eos aut neque.', '2001-06-02', '2013-07-02', '1987-10-23', '22.00', 7);
INSERT INTO `ESDEVENIMENT` (`PK_ID_ESDEVENIMENT`, `NOM`, `DESCRIPCIO`, `HORA`, `DATA_INICI`, `DATA_FI`, `PREU`, `FK_CODI_RECINTE`) VALUES (143, 'a', 'Earum vero sit provident ut sunt autem. Et qui voluptatem itaque dolor ducimus. Voluptate velit dignissimos repellendus iste quia excepturi. Dicta numquam commodi esse magni voluptate soluta ut voluptate. Et qui numquam id.', '1977-05-01', '1982-02-17', '1987-01-29', '5.00', 7);
INSERT INTO `ESDEVENIMENT` (`PK_ID_ESDEVENIMENT`, `NOM`, `DESCRIPCIO`, `HORA`, `DATA_INICI`, `DATA_FI`, `PREU`, `FK_CODI_RECINTE`) VALUES (145, 'ut', 'Ut quo cumque corporis quod. Consequuntur tempora nihil officia molestiae molestiae. Dolores voluptas assumenda magnam libero praesentium. Amet et deleniti quia.', '1986-08-07', '1990-05-26', '1972-01-27', '99999.99', 4);
INSERT INTO `ESDEVENIMENT` (`PK_ID_ESDEVENIMENT`, `NOM`, `DESCRIPCIO`, `HORA`, `DATA_INICI`, `DATA_FI`, `PREU`, `FK_CODI_RECINTE`) VALUES (150, 'corporis', 'Corrupti officiis exercitationem molestiae exercitationem cupiditate. Alias nostrum blanditiis consequatur dicta. Consequatur ratione quia labore totam voluptas autem. Vel illum sit rerum eum similique et ipsum nam.', '1984-02-04', '1990-01-01', '1987-08-31', '47223.00', 15);
INSERT INTO `ESDEVENIMENT` (`PK_ID_ESDEVENIMENT`, `NOM`, `DESCRIPCIO`, `HORA`, `DATA_INICI`, `DATA_FI`, `PREU`, `FK_CODI_RECINTE`) VALUES (152, 'dolore', 'Fugiat cupiditate voluptate veritatis possimus. Molestias quidem assumenda qui at. At ut nihil voluptate sed vel est ut. Et voluptatem suscipit eveniet magni et esse.', '1979-04-30', '2003-09-14', '2007-10-27', '5731.00', 5);
INSERT INTO `ESDEVENIMENT` (`PK_ID_ESDEVENIMENT`, `NOM`, `DESCRIPCIO`, `HORA`, `DATA_INICI`, `DATA_FI`, `PREU`, `FK_CODI_RECINTE`) VALUES (156, 'necessitatibus', 'Error accusamus error et dolorem. Sit aut cumque quis in ut. Voluptas et ex vel odit tempore ut eaque.', '2015-10-11', '1984-07-09', '2002-04-22', '99999.99', 86);
INSERT INTO `ESDEVENIMENT` (`PK_ID_ESDEVENIMENT`, `NOM`, `DESCRIPCIO`, `HORA`, `DATA_INICI`, `DATA_FI`, `PREU`, `FK_CODI_RECINTE`) VALUES (163, 'et', 'Vel sed eius aut. Dolor et officiis et. Hic et ea nisi commodi ea.', '1981-01-06', '2005-09-02', '1994-10-28', '0.00', 80);
INSERT INTO `ESDEVENIMENT` (`PK_ID_ESDEVENIMENT`, `NOM`, `DESCRIPCIO`, `HORA`, `DATA_INICI`, `DATA_FI`, `PREU`, `FK_CODI_RECINTE`) VALUES (164, 'natus', 'Tempore rerum illum aut culpa. Expedita sit placeat aliquam iure. Rem voluptas qui dolores et.', '1996-12-16', '2004-02-15', '1999-02-06', '99999.99', 74);
INSERT INTO `ESDEVENIMENT` (`PK_ID_ESDEVENIMENT`, `NOM`, `DESCRIPCIO`, `HORA`, `DATA_INICI`, `DATA_FI`, `PREU`, `FK_CODI_RECINTE`) VALUES (165, 'magnam', 'Omnis quod et sunt minus libero. Autem ea eaque adipisci fuga. Quia perferendis quam cupiditate enim id aut nihil. A facilis est sit occaecati nostrum est.', '2009-10-11', '1970-02-13', '2000-09-27', '99999.99', 1);
INSERT INTO `ESDEVENIMENT` (`PK_ID_ESDEVENIMENT`, `NOM`, `DESCRIPCIO`, `HORA`, `DATA_INICI`, `DATA_FI`, `PREU`, `FK_CODI_RECINTE`) VALUES (171, 'asperiores', 'Harum eligendi cumque debitis. In aut repellendus odit officia. Iure qui officiis quis aperiam sequi quo ut eum. Aut magni porro ducimus et.', '1993-02-10', '1999-02-24', '2010-04-02', '300.00', 8);
INSERT INTO `ESDEVENIMENT` (`PK_ID_ESDEVENIMENT`, `NOM`, `DESCRIPCIO`, `HORA`, `DATA_INICI`, `DATA_FI`, `PREU`, `FK_CODI_RECINTE`) VALUES (192, 'eum', 'Eius dolorum ea sequi sint quia debitis rerum. Voluptatem esse aut ad ut eaque ea quis in.', '2001-02-28', '2007-07-21', '2005-09-24', '99999.99', 6);
INSERT INTO `ESDEVENIMENT` (`PK_ID_ESDEVENIMENT`, `NOM`, `DESCRIPCIO`, `HORA`, `DATA_INICI`, `DATA_FI`, `PREU`, `FK_CODI_RECINTE`) VALUES (196, 'sequi', 'Optio provident atque perferendis placeat facere id. Praesentium in magni quia. Corporis vel vel perferendis eaque debitis officia dolorum.', '1979-05-25', '1999-12-30', '2016-05-19', '0.00', 9);

/*INSERTS INTO TIPUS_ESDEVENIMENT*/
INSERT INTO `TIPUS_ESDEVENIMENT` (`PK_FK_CODI_TIPUS`, `PK_FK_ID_TIPUS_ESDEVENIMENT`) VALUES (31, 145);

/*INSERTS INTO RESTRICCIO*/
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (316, 171, 'et', 'Provident voluptas eos animi doloribus totam enim sapiente.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (1390, 145, 'velit', 'Quo quas aut consequuntur consequuntur reprehenderit iure.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (2723, 163, 'sed', 'Eveniet illo sapiente qui aut blanditiis cumque.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (2799, 116, 'rerum', 'Consequatur sequi dolorem vitae sit.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (3762, 143, 'est', 'Occaecati voluptas autem deleniti architecto nostrum officia.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (4985, 114, 'sit', 'Commodi minima ex autem ullam ullam et facere voluptate.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (6157, 156, 'nostrum', 'Ut in est sequi et illum voluptas vero.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (6752, 165, 'enim', 'Debitis non ut est eos eum.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (8384, 164, 'inventore', 'Quod expedita est pariatur consequatur placeat.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (8925, 117, 'est', 'Numquam consequatur corrupti placeat eaque repellat non.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (9572, 103, 'eligendi', 'Animi non et repudiandae est sint magnam hic totam.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (10139, 135, 'error', 'Quos et in culpa ad nam.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (12120, 127, 'commodi', 'Repellat ratione doloribus cupiditate consequatur.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (12334, 192, 'quia', 'Ut ipsa ut voluptas assumenda enim maxime.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (13960, 196, 'sunt', 'Alias iste qui aliquam voluptatem ut sapiente nihil.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (14567, 150, 'qui', 'Incidunt nobis perferendis totam qui voluptatem doloribus.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (18310, 105, 'placeat', 'Et temporibus eum id non mollitia consequatur et.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (20768, 107, 'adipisci', 'Id ut qui voluptates non.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (26379, 128, 'rem', 'Ipsum rem qui ex facere quibusdam.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (27192, 139, 'qui', 'Ad dignissimos qui hic blanditiis.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (39730, 152, 'eum', 'Neque et rerum consequuntur officia et.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (40732, 150, 'magni', 'Ut quae quae quas.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (40921, 135, 'deserunt', 'Natus dignissimos sequi omnis ipsa aperiam est alias.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (41516, 107, 'quia', 'Dignissimos expedita amet ut architecto.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (41597, 156, 'maxime', 'Quia est quis nesciunt.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (41751, 171, 'laboriosam', 'Corporis id eum suscipit omnis.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (45103, 105, 'placeat', 'Facilis necessitatibus enim unde voluptatibus voluptatem dicta temporibus voluptates.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (46103, 145, 'alias', 'Aut temporibus occaecati doloribus hic facere quas.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (48912, 196, 'ea', 'Doloribus asperiores ut labore dicta tempora.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (49400, 114, 'nesciunt', 'Dolorum facere sunt saepe tenetur ullam suscipit.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (49505, 103, 'aut', 'Dicta dolores quae vero voluptatum consequatur quisquam earum et.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (49719, 143, 'aut', 'Mollitia dolores consequatur numquam et sed provident occaecati.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (52320, 163, 'accusantium', 'Aperiam molestiae modi quia voluptatem architecto.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (53733, 139, 'nesciunt', 'Aut maiores rem molestias ad cumque.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (55767, 116, 'ut', 'Asperiores sit inventore mollitia.');
INSERT INTO `RESTRICCIO` (`PK_CODI_RESTRICCIO`, `PK_FK_ID_RESTRICCIO_ESDEVENIMENT`, `TIPUS_RESTRICCIO`, `DESCRIPCIO`) VALUES (57919, 152, 'sed', 'Amet rem ab dolorem saepe ut.');

/*INSERTS INTO BUTACA*/
INSERT INTO `BUTACA` (`PK_FK_CODI_RECINTE`, `PK_FILA_BUTACA`, `PK_NUMERO_BUTACA`) VALUES (3, 0, 7008);
INSERT INTO `BUTACA` (`PK_FK_CODI_RECINTE`, `PK_FILA_BUTACA`, `PK_NUMERO_BUTACA`) VALUES (6, 2356, 3899918);
INSERT INTO `BUTACA` (`PK_FK_CODI_RECINTE`, `PK_FILA_BUTACA`, `PK_NUMERO_BUTACA`) VALUES (8, 2, 2964);
INSERT INTO `BUTACA` (`PK_FK_CODI_RECINTE`, `PK_FILA_BUTACA`, `PK_NUMERO_BUTACA`) VALUES (17, 10503, 27563038);
INSERT INTO `BUTACA` (`PK_FK_CODI_RECINTE`, `PK_FILA_BUTACA`, `PK_NUMERO_BUTACA`) VALUES (24, 122, 1524530);
INSERT INTO `BUTACA` (`PK_FK_CODI_RECINTE`, `PK_FILA_BUTACA`, `PK_NUMERO_BUTACA`) VALUES (52, 29, 497);
INSERT INTO `BUTACA` (`PK_FK_CODI_RECINTE`, `PK_FILA_BUTACA`, `PK_NUMERO_BUTACA`) VALUES (56, 45385, 8965950);
INSERT INTO `BUTACA` (`PK_FK_CODI_RECINTE`, `PK_FILA_BUTACA`, `PK_NUMERO_BUTACA`) VALUES (76, 42834888, 1668);
INSERT INTO `BUTACA` (`PK_FK_CODI_RECINTE`, `PK_FILA_BUTACA`, `PK_NUMERO_BUTACA`) VALUES (91, 43, 3617);
INSERT INTO `BUTACA` (`PK_FK_CODI_RECINTE`, `PK_FILA_BUTACA`, `PK_NUMERO_BUTACA`) VALUES (97, 3462, 443209);